"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['zanshin-wallet.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': '/Users/aaraybin/Documents/py4e/mygit/zanshin-wallet-distr/zsh.icns',
    'packages': ['flask', 'werkzeug', 'config', 'jinja2','requests','flask_cors','json', 'uuid', 'Crypto','blockchain','createWallet','authoriseUser','signTransaction'], #'os','re','sys','pickle','webbrowser','time','datetime','hashlib' ,,  ,'json',
    'resources': ['./templates', './static']
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
